version: '3.4'

x-app-volume:
  &app
  type: bind
  source: ./app/
  target: /code/app/
  consistency: cached

services:
  app:
    build:
      context: .
      dockerfile: $PWD/containers/app/Dockerfile.dev
    image: &app_image app
    depends_on:
      postgres:
        condition: service_healthy
    links: 
      - postgres
    volumes:
      - *app
      - $PWD/data:/code/data
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - $PWD/containers/app/.env
      - $PWD/containers/postgres/.env

  postgres:
    image: postgres:15.2
    volumes:
      - postgresql-database:/var/lib/postgresql/data:delegated
    ports:
    - "5432:5432"
    env_file:
    - $PWD/containers/postgres/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5


volumes:
  postgresql-database:
    name: postgresql-database
